### ISSUE TITLE
database.yml の設定ができたかどうかわからない。何の反応も特別得られず困っている

### ISSUE THREAD

**Issue by TetsuTatsu** [TetsuTatsu/nicoap#1]

**Comment by yancya** [comment]
ちゃんと設定できてると、`rails db` を実行したときにデータベースのコンソールに入れる

**Comment by TetsuTatsu** [comment]
rails db →OK
↓
NG（エラー
↓
「pgがないぞ」
↓
Gemfileに'pg'を追加
↓
「サーバーがないぞ」
↓
postgresql 10.1 → 9.5.3（brew switch）
↓
「権限がないぞ」
↓
権限を追加
↓
rails db:create
↓
ymlエラー
↓
データベース名を変更
↓
rails db:create
↓
rails db
↓
OK
